# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [11, 8]

    steps:
    - uses: actions/checkout@v2.1.0

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1.3.0
      with:
        java-version: ${{ matrix.java }}

    - uses: actions/cache@v1.1.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Patch Sekiei
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git submodule update --init --recursive
        ./sekiei jar
        
    - uses: actions/upload-artifact@v2
      with:
        name: Sekiei-JDK${{ matrix.java }}
        path: sekiei-1.16.2.jar
